import os

from dotenv import load_dotenv
from google.generativeai import GenerativeModel, configure

# Load environment variables from the .env file
load_dotenv()

# Configure the Google Generative AI SDK using the API key stored in .env
configure(api_key=os.getenv("GEMINI_API_KEY"))

# Initialize the Gemini model from GEMINI_MODEL in .env
model = GenerativeModel(os.getenv("GEMINI_MODEL"))


def gemini_response(prompt: str):
    """
    Generate a response from the Gemini model based on the provided prompt.

    Args:
        prompt (str): The user input or query.

    Returns:
        str: The text output generated by the model.
    """

    # Send the prompt to Gemini and retrieve the structured response
    result = model.generate_content(prompt)

    # Extract and return only the generated text
    return result.text